### ISSUE TITLE
Provision a new page va.gov/performance-dashboard  for the new VA Performance Dashboard

### ISSUE THREAD

**Issue by rumyeahs** [department-of-veterans-affairs/vets.gov-status#3195]
**User Story or Problem Statement**
As a member of the Office of the CTO, I need a distinct space on VA.gov that talks about Performance of va.gov so I can point senior stakeholders and other members of the VA to this space for viewing any relevant metrics of VA.gov

**Goal**

- Any member visiting the VA.gov/performance-dashboard  will see a page titled VA.gov Performance Dashboard
- Additional metrics will be built upon in follow-up stories

**Tasks**
- [ ] Create url dev.va.gov/performance-dashboard - pointing to same s3 bucket as /scorecard
- [ ] Create url staging.va.gov/performance-dashboard - pointing to same s3 bucket as /scorecard
- [ ] Create the new url va.gov/performance-dashboard - pointing to same s3 bucket as /scorecard
- [ ] See the same content on scorecard within the /performance-dashboard page

**Acceptance Criteria**
 What will be created or happen as a result of this story?

For tracking:
[Redirect issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/6928)
[Changing footer links issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/6933)

**Comment by philherbert** [comment]
https://github.com/department-of-veterans-affairs/vets-website/search?q=scorecard&unscoped_q=scorecard

**Comment by karlbrown-va** [comment]
Mikki is looking at the options here.

**Comment by kennedycollins** [comment]
per @mnorthuis and @KevinMHoffmanUSDS, the long term plan is to get this over to some kind of subdomain; but because that's going to take some time we're going to make the intermediate move to /performance-dashboard

**Comment by kennedycollins** [comment]
I've created issues for the redirect and the va.gov footer updates; they're linked above for context. This ticket is specifically for tracking the actual creation of /performance-dashboard and pointing it to the right s3 bucket, which is our responsibility.

**Comment by rumyeahs** [comment]
Need to make a PR against the related DevOps issue

**Comment by karlbrown-va** [comment]
Have requested write access to the devops repo. Awaiting approval.

**Comment by karlbrown-va** [comment]
PR submitted

**Comment by karlbrown-va** [comment]
PR is merged so the new URL exists now. Keeping this open until the other PRs close as well.
