### ISSUE TITLE
Implement CSAT scores for all service line tiles

### ISSUE THREAD

**Issue by rumyeahs** [department-of-veterans-affairs/vets.gov-status#3232]
**As** a member of the Office of the CTO
**I want to** present a view of customer satisfaction across various VA.gov education related and other services and tools
**so that** any visitor (such as a senior VA stakeholder) to the dashboard gets an insight into how the veteran experience has been with the education services on the portal

**Tasks:**
* Pull CSAT scores across all VA.gov education related pages, for the last 30 days from Foresee (url: www.va.gov/education or www.va.gov/gi-bill) 
* Display the average CSAT score for the last 30 days in bold within the education tile (as illustrated in attached design)
* Display a trend indicator on how the average CSAT score of the last 30 days compares with the average CSAT score for the same period of 30 days from the previous year, across education services and tools
* Include necessary description for 508 compliance
* Include CSAT scores for the other service line tiles for Health care, Disability, Pension, Profile & Records

**Acceptance Criteria**
**Given** any user
**When** he/she visits the dashboard
**Then** the visitor sees the average CSAT score for the last 30 days within the Education section

**Given** any user
**When** he/she visits the dashboard
**Then** the visitor sees the CSAT score trend in percentage, alongwith an indicator, of how the last 30 days average CSAT score compares against the average CSAT score for the same period from the previous year

**Given** the data refresh job is run 
**When** there is an error updating the chart value
**Then**
- Exit with error code = 1
- Do not refresh the data on the chart and retain the old values
- Do not update the last updated date

![Screen Shot 2020-03-18 at 8.15.28 AM.png](https://images.zenhubusercontent.com/5dc98bd276ca1300019e1a85/23713535-9474-4f2b-ab82-677f489382af)

**Comment by shefalinayak** [comment]
Implementation notes:
- [ ]  Send two requests to Foresee API for the two 30-day periods
- [ ]  Store data in dataframes
- [ ]  Per service filter data by pagePath/url and calculate year-over-year trend
- [ ]  Write scores and trends into counts.yml
